config/routes.rb
LinkedInAggregator::Application.routes.draw do
  resources :pools do
    member do
      get 'search/:search', to: 'pools#search'
    end
  end

  root to: 'pools#index'
  get '/:invite_key', to: 'pools#invite', as: 'invite'
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :connections
  resources :positions
  resources :users

  

end

app/models/pool.rb
class Pool < ActiveRecord::Base
  before_save :generate_invite_key

  belongs_to :owner, class_name: 'User'

  has_and_belongs_to_many :users
  has_many :connections, through: :users

  validates_presence_of :name

  private
  def generate_invite_key
    unless self.invite_key
      self.invite_key = SecureRandom.uuid
      self.invite_url =
          Googl.shorten(Rails.application.routes.url_helpers.invite_url(self.invite_key)).short_url
    end
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :set_pool, only: [:show, :edit, :update, :destroy]

  # GET /aggregators
  # GET /aggregators.json
  def index
    if @current_user
      @pools = @current_user.pools
    else
      render :splash
    end
  end

  def search
    @pool = @current_user.pools.find_by(id: params[:id])
    results = []
    Connection.search(params[:search], where: {id: @pool.connections.map(&:id)}).each do |connection|
      next if connection.profile == nil
      results.push connection.profile
    end
    render json: results
  end

  # GET /aggregators/1
  # GET /aggregators/1.json
  def show
    @pool = @current_user.pools.find_by(id: params[:id])
    render layout: 'angular'
  end

  def invite
    @pool = Pool.find_by_invite_key(params[:invite_key])
    session[:invite_key] = params[:invite_key]
  end

  # GET /aggregators/new
  def new
    @pool = Pool.new
  end

  # GET /aggregators/1/edit
  def edit
  end

  # POST /aggregators
  # POST /aggregators.json
  def create
    @pool = Pool.new(pool_params)
    @pool.owner = @current_user
    @pool.users.push @current_user

    respond_to do |format|
      if @pool.save
        format.html { redirect_to pool_path(@pool), notice: 'Aggregator was successfully created.' }
        format.json { render action: 'show', status: :created, location: pool_path(@pool) }
      else
        format.html { render action: 'new' }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aggregators/1
  # PATCH/PUT /aggregators/1.json
  def update
    respond_to do |format|
      if @pool.update(pool_params)
        format.html { redirect_to @pool, notice: 'Aggregator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aggregators/1
  # DELETE /aggregators/1.json
  def destroy
    @pool.destroy
    respond_to do |format|
      format.html { redirect_to aggregators_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pool
      @pool = Pool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pool_params
      params.require(:pool).permit(:name)
    end
end

app/views/pools/_form.html.erb
<%= form_for @pool do |f| %>
  <% if @pool.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @pool.errors.full_messages.each do |msg| %>
        <li class="error"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder: 'Name' %>
  </div>
  <div class="actions">
    <%= f.submit 'Create', class: 'button' %>
  </div>
<% end %>

app/views/pools/edit.html.erb
<h1>Editing aggregator</h1>

<%= render 'form' %>

<%= link_to 'Show', @aggregator %> |
<%= link_to 'Back', aggregators_path %>

app/views/pools/index.html.erb
<div class="pools">

  <h2>Choose a Pool</h2>

  <ul>
    <% @pools.each do |pool| %>
        <li><%= link_to pool.name, pool_path(pool) %>
          <% if pool.owner == @current_user %><span>(Owner)</span><% end%></li>
    <% end %>
    <li><%= link_to 'Start a New Pool', new_pool_path %></li>
  </ul>

</div>

app/views/pools/invite.html.erb
<div class="invite">
  <h2>You've been invited</h2>

  <p>You've been invited to share your LinkedIn connections at <%= @pool.name %></p>
  <p style="text-align: center;"><%= link_to 'Get Started', '/auth/linkedin' %></p>
</div>

app/views/pools/new.html.erb
<div class="pools">

  <h2>Start a New Pool</h2>

  <%= render 'form' %>

</div>

app/views/pools/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @pool.name %></h1>

<p>
  <strong>Invite key:</strong>
  <%= link_to @pool.invite_url, @pool.invite_url %>
</p>

app/views/pools/splash.html.erb
<%= link_to 'Log In', '/auth/linkedin' %>