config/routes.rb
LinkedInAggregator::Application.routes.draw do
  resources :pools do
    member do
      get 'search/:search', to: 'pools#search'
    end
  end

  root to: 'pools#index'
  get '/:invite_key', to: 'pools#invite', as: 'invite'
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :connections
  resources :positions
  resources :users

  

end

app/models/connection.rb
class Connection < ActiveRecord::Base
  searchkick

  belongs_to :user

  validates_uniqueness_of :linkedin_id
  has_and_belongs_to_many :users

  def should_crawl?
    last_crawled == nil || Time.now - 1.day > last_crawled
  end

end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  before_action :set_connection, only: [:show, :edit, :update, :destroy]

  # GET /connections
  # GET /connections.json
  def index

    user = 2#get_current_user
    
    if user
      @aggregator = Pool.find_by_owner_id(user)
      results = []
      Connection.where(user_id: @aggregator.users).each do |connection|

        next if connection.profile == nil

        profile = connection.profile
        profile[:first_name] = connection.first_name
        profile[:last_name] = connection.last_name
        profile[:headline] = connection.headline
        results.push profile
      end
      render json: {profiles: results};
    end

  end

  # GET /connections/1
  # GET /connections/1.json
  def show
  end

  # GET /connections/new
  def new
    @connection = Connection.new
  end

  # GET /connections/1/edit
  def edit
  end

  # POST /connections
  # POST /connections.json
  def create
    @connection = Connection.new(connection_params)

    respond_to do |format|
      if @connection.save
        format.html { redirect_to @connection, notice: 'Connection was successfully created.' }
        format.json { render action: 'show', status: :created, location: @connection }
      else
        format.html { render action: 'new' }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /connections/1
  # PATCH/PUT /connections/1.json
  def update
    respond_to do |format|
      if @connection.update(connection_params)
        format.html { redirect_to @connection, notice: 'Connection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /connections/1
  # DELETE /connections/1.json
  def destroy
    @connection.destroy
    respond_to do |format|
      format.html { redirect_to connections_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_connection
      @connection = Connection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def connection_params
      params.require(:connection).permit(:first_name, :last_name, :headline)
    end
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/views/connections/_form.html.erb
<%= form_for(@connection) do |f| %>
  <% if @connection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@connection.errors.count, "error") %> prohibited this connection from being saved:</h2>

      <ul>
      <% @connection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :headline %><br>
    <%= f.text_field :headline %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/connections/edit.html.erb
<h1>Editing connection</h1>

<%= render 'form' %>

<%= link_to 'Show', @connection %> |
<%= link_to 'Back', connections_path %>

app/views/connections/index.html.erb
<h1>Listing connections</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Headline</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @connections.each do |connection| %>
      <tr>
        <td><%= connection.first_name %></td>
        <td><%= connection.last_name %></td>
        <td><%= connection.headline %></td>
        <td><%= link_to 'Show', connection %></td>
        <td><%= link_to 'Edit', edit_connection_path(connection) %></td>
        <td><%= link_to 'Destroy', connection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Connection', new_connection_path %>

app/views/connections/new.html.erb
<h1>New connection</h1>

<%= render 'form' %>

<%= link_to 'Back', connections_path %>

app/views/connections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @connection.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @connection.last_name %>
</p>

<p>
  <strong>Headline:</strong>
  <%= @connection.headline %>
</p>

<%= link_to 'Edit', edit_connection_path(@connection) %> |
<%= link_to 'Back', connections_path %>