config/routes.rb
LinkedInAggregator::Application.routes.draw do
  resources :pools do
    member do
      get 'search/:search', to: 'pools#search'
    end
  end

  root to: 'pools#index'
  get '/:invite_key', to: 'pools#invite', as: 'invite'
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :connections
  resources :positions
  resources :users

  

end

app/models/position.rb
class Position < ActiveRecord::Base

  validates_uniqueness_of :title, scope: [:organization, :connection_id]

  belongs_to :connection

end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render action: 'show', status: :created, location: @position }
      else
        format.html { render action: 'new' }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:title, :organization, :connection_id)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :organization %><br>
    <%= f.text_field :organization %>
  </div>
  <div class="field">
    <%= f.label :connection %><br>
    <%= f.text_field :connection %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<h1>Listing positions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Organization</th>
      <th>Connection</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.title %></td>
        <td><%= position.organization %></td>
        <td><%= position.connection %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New position</h1>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @position.title %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @position.organization %>
</p>

<p>
  <strong>Connection:</strong>
  <%= @position.connection %>
</p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>